modLoader = "javafml"
loaderVersion = "[1,)"
license="MIT"

issueTrackerURL="https://github.com/OffsetMods538/MESH-Lib/issues"


[[mods]]
modId="mesh_lib"
displayName="MESH Lib"
version="${modVersion}"
displayURL="https://modrinth.com/mod/mesh-lib"
authors="OffsetMonkey538"
description="A library mod for OffsetMonkey538s mods"

[[mixins]]
config="mesh-lib.mixins.json"


[[dependencies.mesh_lib]]
modId="minecraft"
type="required"
versionRange="${supportedMinecraftVersions}"
ordering="NONE"
side="BOTH"

[[dependencies.mesh_lib]]
modId="monkeylib538_common_neoforge"
type="required"
versionRange="[${currentMonkeylibVersion},)"
ordering="NONE"
side="BOTH"
