name: Publish docs

on:
  push:
    branches:
      - "docs/*"


jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Store short commit hash
        run: echo "short_commit_hash=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - name: Set up NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: latest
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build docs for commit
        run: pnpm run build
        env:
          CUSTOM_SITE_ENV: "https://${{ env.short_commit_hash }}.mesh-lib.docs.offsetmonkey538.top/"

      - name: Upload docs for commit to actions
        uses: actions/upload-artifact@v6
        with:
          name: Commit
          path: dist/

      - name: Upload docs for commit to docs host
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.ORACLE_DOCS_HOST }}
          username: ${{ secrets.ORACLE_DOCS_USER }}
          port: ${{ secrets.ORACLE_DOCS_PORT }}
          key: ${{ secrets.ORACLE_DOCS_SSH_KEY }}
          passphrase: ${{ secrets.ORACLE_DOCS_SSH_KEY_PASSPHRASE }}
          source: "dist/*"
          target: "~/docs/mesh-lib/commit/${{ env.short_commit_hash }}"
          strip_components: 1
          rm: true


      - name: Delete built docs before building again
        run: rm -rf dist


      - name: Build docs for latest
        if: ${{ github.ref_name == 'docs/master' }}
        run: pnpm run build
        env:
          CUSTOM_SITE_ENV: "https://mesh-lib.docs.offsetmonkey538.top/"

      - name: Upload docs for latest to actions
        if: ${{ github.ref_name == 'docs/master' }}
        uses: actions/upload-artifact@v6
        with:
          name: Latest
          path: dist/

      - name: Upload docs for latest to docs host
        if: ${{ github.ref_name == 'docs/master' }}
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.ORACLE_DOCS_HOST }}
          username: ${{ secrets.ORACLE_DOCS_USER }}
          port: ${{ secrets.ORACLE_DOCS_PORT }}
          key: ${{ secrets.ORACLE_DOCS_SSH_KEY }}
          passphrase: ${{ secrets.ORACLE_DOCS_SSH_KEY_PASSPHRASE }}
          source: "dist/*"
          target: "~/docs/mesh-lib/latest"
          strip_components: 1
          rm: true
